name: tomi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  hive: ^2.2.3
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.1.4
  retry: ^3.1.2
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  hive_flutter: ^1.1.0
  email_validator: ^3.0.0
  auto_route: ^10.0.1
  shimmer: ^3.0.0
  flutter_screenutil:
  flutter_staggered_animations:
  cached_network_image: ^3.4.1
  url_launcher:
  webview_flutter: ^4.13.0
  flutter_secure_storage: ^9.2.4
  dotted_decoration: ^2.0.0
  dropdown_button2: ^2.3.9
  file_picker: ^10.1.9
  iconsax_flutter:

dependency_overrides:
  source_gen: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
  freezed: ^3.0.6
  auto_route_generator: ^10.0.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true